name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: AZUREPAT
    steps:
    #- uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}

     # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          git clone git@ssh.dev.azure.com:v3/sathyapinreddy/Dot-Net-Demo/synctest
          git remote add github git@github.com:sathya111/ADO-SYNC.git
          git fetch github
          git push git@ssh.dev.azure.com:v3/sathyapinreddy/Dot-Net-Demo/synctest github/main:main --force

          

